"""
Django settings for kshfplast project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="test")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG",cast=bool,default=True)

#allowed hosts
ALLOWED_HOSTS = ["mysite-amirhosseinkashaf.liara.run",
    "localhost",
    "127.0.0.1",
    ]


SITE_ID = 2



# Application definition

INSTALLED_APPS = [
    'multi_captcha_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
    'blog',
    'accounts',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    # 'django_summernote',
    'captcha',
    'taggit',
    'robots',
    'debug_toolbar',
    'tinymce',
    'compressor',
    
]


# robots
ROBOTS_USE_HOST = False

ROBOTS_USE_SITEMAP = False

MULTI_CAPTCHA_ADMIN = {
    'engine' : 'simple-captcha',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'kshfplast.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kshfplast.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE",default="django.db.backends.postgresql"),
        "NAME": config("DB_NAME",default="postgres"),
        "USER": config("DB_USER",default="postgres"),
        "PASSWORD": config("DB_PASS",default="postgres"),
        "HOST": config("DB_HOST",default="127.0.0.1"),
        "PORT": config("DB_PORT",cast=int,default=5432),
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG
}


# Static files (CSS, JavaScript, Images)sadad
# https://docs.djangoproject.com/en/4.2/howto/static-files/


MEDIA_ROOT = 'media'
STATIC_ROOT = 'static'
STATICFILES_DIRS = [
    BASE_DIR / 'statics',
]

STATIC_URL = '/static/'
MEDIA_URL = '/media/'


INTERNAL_IPS = {
    '127.0.0.1',
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Email configuration
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Use SMTP for production
    EMAIL_HOST = 'smtp.gmail.com'  # Replace with your email provider's SMTP server
    EMAIL_PORT = 587  # Port for TLS
    EMAIL_USE_TLS = True  # Use TLS for secure connection
    EMAIL_HOST_USER = 'kashafamirhossein@gmail.com'  # Your email address
    EMAIL_HOST_PASSWORD = 'smgj rjxe qnre fcaa'
    DEFAULT_FROM_EMAIL = 'kashafamirhossein@gmail.com'  # Default sender email


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
#compress settings
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True  # Enable offline compression (optional)
COMPRESS_ROOT = BASE_DIR / 'static'  # Should match your STATIC_ROOT
COMPRESS_STORAGE = 'compressor.storage.CompressorFileStorage'


# CSS compression settings
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]

# JavaScript compression settings
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',
]
if not DEBUG:  # Only enforce HTTPS in production
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# These can stay outside the DEBUG check
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_REFERRER_POLICY = "strict-origin"
USE_X_FORWARDED_HOST = True